name: CI

on: [push]

jobs:
  build-humanitec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push to Humanitec
        uses: humanitec/build-push-to-humanitec@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: ${{ vars.HUMANITEC_ORG }}
  run-score:
    runs-on: ubuntu-latest
    needs: build-humanitec

    steps:
      - uses: actions/checkout@v3

      - name: Install score-humanitec
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/0.7.0/score-humanitec_0.7.0_linux_amd64.tar.gz
          tar -xvf score-humanitec_0.7.0_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin

      - name: Run Score
        run: |
          if [ -f score.yaml ]
          then 
            sed -i -E "s/^(\\s+image:)\\s+.*\$/\\1 'registry.humanitec.io\\/${{ vars.HUMANITEC_ORG }}\\/${GITHUB_REPOSITORY##*/}:${GITHUB_SHA}'/" score.yaml
            score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app jotd --env development
          else
            echo "no score file found, cannot deploy"
            exit 1
          fi
