name: Main
on:
  push:
    branches:
      - "main"
      - "demo"
permissions:
  contents: read
  pull-requests: write
env:
  ENVIRONMENT: 'development'
  SCORE_HUMANITEC_VERSION: 0.9.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push to Humanitec
        uses: humanitec/build-push-to-humanitec@v1
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: ${{ vars.HUMANITEC_ORG }}
      - name: Install score-humanitec
        run: |
          wget https://github.com/score-spec/score-humanitec/releases/download/${{ env.SCORE_HUMANITEC_VERSION }}/score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          tar -xvf score-humanitec_${{ env.SCORE_HUMANITEC_VERSION }}_linux_amd64.tar.gz
          chmod +x score-humanitec
          mv score-humanitec /usr/local/bin
      - name: Run Score
        run: |
          if [ -f score.yaml ]
          then
            sed -i -E "s/^(\\s+image:)\\s+.*\$/\\1 'registry.humanitec.io\\/${{ vars.HUMANITEC_ORG }}\\/${GITHUB_REPOSITORY##*/}:${GITHUB_SHA}'/" score.yaml
            score-humanitec delta \
              --retry \
              --deploy \
              --token ${{ secrets.HUMANITEC_TOKEN }} \
              --org ${{ vars.HUMANITEC_ORG }} \
              --app ${{ vars.HUMANITEC_APP }} \
              --env ${{ env.ENVIRONMENT }} \
              | tee score_output.json
          else
            echo "no score file found, cannot deploy"
            exit 1
          fi
